name: Variables and Secrets
on: [push]

jobs:
  log-vars:
    runs-on: ${{ vars.JOBS_RUNNER }}
    env:
      JOBS_RUNNER: ${{ vars.JOBS_RUNNER }}
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: env.JOBS_RUNNER == 'JOBS_RUNNER'
        run: echo "I ran on JOBS_RUNNER"
      - name: Log Vars
        run: |
          echo '${{ vars.JOBS_RUNNER }}'
          echo "ORG_LEVEL_VAR: $ORG_LEVEL_VAR"
          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"